name: streetmarket
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  iconsax: ^0.0.8
  flutter_neumorphic: ^3.0.3
  google_fonts: ^2.1.0
  cupertino_icons: ^1.0.2
  firebase_core: ^2.13.0
  firebase_auth: ^4.6.1
  cloud_firestore: ^4.7.1
  provider: ^6.0.5
  image_picker: ^0.8.7+5
  firebase_storage: ^11.2.1
  flutter_image: ^4.1.6
  uuid: ^3.0.7
  # firestore_search_input: ^0.2.0

  firestore_search_input:
    git:
      url: https://github.com/JohnEsleyer/firestore_search_input
  url_launcher: ^6.1.11
  maps_launcher: ^2.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
       - assets/
       - assets/streetmarket_icon.png
       - assets/streetmarket_text.png
       - assets/background.jpg
       - assets/icon2.png
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
