// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCW8GEXFREJejz5iN8EAjG0sBh9tcucO20',
    appId: '1:43711531729:web:7d0b5d81023a28dde1d3f0',
    messagingSenderId: '43711531729',
    projectId: 'streetmarket-7a53f',
    authDomain: 'streetmarket-7a53f.firebaseapp.com',
    storageBucket: 'streetmarket-7a53f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9hlq6BdRIsZHSCLGfzBxVAmpt6KP08ew',
    appId: '1:43711531729:android:71e422564aabdca4e1d3f0',
    messagingSenderId: '43711531729',
    projectId: 'streetmarket-7a53f',
    storageBucket: 'streetmarket-7a53f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArnmsZj9OvxsrCCbcNLXBr1sPz9t103Vk',
    appId: '1:43711531729:ios:b598db4c3f31f49be1d3f0',
    messagingSenderId: '43711531729',
    projectId: 'streetmarket-7a53f',
    storageBucket: 'streetmarket-7a53f.appspot.com',
    iosClientId: '43711531729-7p6k33nblffuivkflr4b6vf723775o1s.apps.googleusercontent.com',
    iosBundleId: 'com.example.streetmarket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArnmsZj9OvxsrCCbcNLXBr1sPz9t103Vk',
    appId: '1:43711531729:ios:b598db4c3f31f49be1d3f0',
    messagingSenderId: '43711531729',
    projectId: 'streetmarket-7a53f',
    storageBucket: 'streetmarket-7a53f.appspot.com',
    iosClientId: '43711531729-7p6k33nblffuivkflr4b6vf723775o1s.apps.googleusercontent.com',
    iosBundleId: 'com.example.streetmarket',
  );
}
